graph TD
    _NETStandard1_0[[.NETStandard1.0]]
    _NETStandard1_0 --> Microsoft_CSharp_4_3_0
    _NETStandard1_0 --> NETStandard_Library_1_6_1
    _NETStandard1_0 --> System_ComponentModel_TypeConverter_4_3_0
    _NETStandard1_0 --> System_Runtime_Serialization_Primitives_4_3_0
    _NETStandard1_3[[.NETStandard1.3]]
    _NETStandard1_3 --> Microsoft_CSharp_4_3_0
    _NETStandard1_3 --> NETStandard_Library_1_6_1
    _NETStandard1_3 --> System_ComponentModel_TypeConverter_4_3_0
    _NETStandard1_3 --> System_Runtime_Serialization_Formatters_4_3_0
    _NETStandard1_3 --> System_Runtime_Serialization_Primitives_4_3_0
    _NETStandard1_3 --> System_Xml_XmlDocument_4_3_0